site_name: Management Portal Documentation

nav: 
  - 'index.md'
  - Members:
    - 'developer-and-teams-member/index.md'
    - Sign up and Account Settings: 'general/signin-and-settings.md'
    - Homepage Functionalities: 'general/main.md'
    - Member Functionalities: 'general/basic-team.md'
    - Connect qodo Merge: 'general/qodo-Merge.md'
  - Team Administrators:
    - 'teams-admin/index.md'
    - Sign up and Account Settings: 'general/signin-and-settings.md'
    - Homepage Functionalities: 'general/main.md'
    - Connect qodo Merge: 'general/qodo-Merge.md'
    - Team Member Functionalities: 'general/basic-team.md'
    - Team Admin Functionalities: 'teams-admin/manage-team.md'
    - Manage Teams' Plan: 'teams-admin/manage-plan.md'
  - Organization Administrators:
    - 'enterprise-admin/index.md'
    - Sign up and Account Settings: 'general/signin-and-settings.md'
    - Homepage Functionalities: 'general/main.md'
    - Connect qodo Merge: 'general/qodo-Merge.md'
    - Team Member Functionalities: 'general/basic-team.md'
    - Team Admin Functionalities: 'teams-admin/manage-team.md'
    - Insights & Dashboard: 'enterprise-admin/dashboard.md'
    - Invite-Only Organization: 'enterprise-admin/invite-only.md'
    - Manage Environmets: 'enterprise-admin/manage-environments.md'


theme:
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  language: en
  custom_dir: overrides
    
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
    
    

plugins:
  - social
  - search
  - glightbox
  
  - mkdocs-video:
      css_style:
        position: relative;
        width: "70%"
        height: "22.172vw"
        margin-left: "auto"
        margin-right: "auto"
        display: "block"

extra:
  generator: false
  analytics:
    provider: custom
    property: ${{ secrets.GOOGLE_ANALYTICS_ID }}
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Codium-ai
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SgSxuQ65GF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Codium-AI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codiumai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CodiumAI
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/codiumai/

extra_css:
  - css/custom.css

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page
      toc_depth: 2
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


copyright: |
  &copy; 2024 <a href="https://www.qodo.ai/"  target="_blank" rel="noopener">Qodo</a>
